### ISSUE TITLE
Will Ocen Audio and the Ocen framework be released as open-source free software ?

### ISSUE THREAD

**Issue by Robbt** [ocenaudio/ocenaudio-translations#12]
Hello, I'm not sure this is the right place to ask this question but in search for a simpler alternative to Audacity for editing audio I found OcenAudio and saw it was a research project based out of a Federal University of Santa Catarina (LINSE) in Brazil. I wanted to inquire as to whether there was a plan to release the project with a free software license at some point in the future. I think that it would be highly useful for small community radio stations because Audacity can be overly complex but I am not sure I want to recommend a project that isn't free software and we couldn't modify for our own ends. Can you provide any insight as to the plans for the project and whether this is a possibility. Thanks.

**Comment by falkTX** [comment]
I would like to know as well.
There does not seem to be a lot of development going on at the moment.
Maybe the best would be to let the community take over a bit? It would be a shame that a great tool just ends up being forgotten.

**Comment by guidefloripa** [comment]
Ocenaudio is a free software (non-cost software), but not open source. The Ocen framework, which is the Ocenaudio's basis, is a framework developed in cooperation with a telecom company. In a short term, we can't open the source. But the team is still working on improving Ocenaudio's stability, feature set and user experience.

**Comment by falkTX** [comment]
That is a bummer.
It misses out on many possible community contributions by making it close-source.
Also reduces a lot the number of people that use it, because it cannot be made available in regular Linux distributions. You have to package it yourself to many different distributions, this work could be avoided.

**Comment by ghost** [comment]
Do you think of considering ocenaudio as free (freedom) software in the future?

**Comment by j-rodman** [comment]
> Ocenaudio is a free software (non-cost software), but not open source. The Ocen framework, which is the Ocenaudio's basis, is a framework developed in cooperation with a telecom company. In a short term, we can't open the source. But the team is still working on improving Ocenaudio's stability, feature set and user experience.

The common usage of Free Software means that it is free to modify and redistribute.  Your software appears to be zero-cost, or "freeware".    That's fine, of course.  Everyone who makes software gets to choose their own license, but using the right terms is best.

**Comment by jamesford42** [comment]
So, "ocen framework" can't be open source, fine. But why does that mean "ocenaudio" cannot be? Is "ocen framework" a library for audio data analysis, editing, playback .. or is it also the whole editor ui?

**Comment by jamesford42** [comment]
> Ocenaudio is a free software (non-cost software), but not open source. The Ocen framework, which is the Ocenaudio's basis, is a framework developed in cooperation with a telecom company. In a short term, we can't open the source. But the team is still working on improving Ocenaudio's stability, feature set and user experience.

So _ocen framework_ can't be open source. Fine, makes sense [though, actually contacting them about it would also be appropriate]. But why does that mean _ocenaudio_ cannot be? Does this framework include the entire editor, gui toolset, and all the editors features? Or is this a general audio processing/editing/playback library that can be its own, separate, private repo?
