### ISSUE TITLE
installer strings

### ISSUE THREAD

**Issue by bovirus** [ocenaudio/ocenaudio-translations#20]
@guidefloripa 

I propose you to add in github repository a section about strings used in the installer.

Other translators can provide you the translation for more languages and you can improve the installer.

Thanks.

**Comment by guidefloripa** [comment]
I'll share this idea with the team

**Comment by bovirus** [comment]
@guidefloripa 

For this moment could you pelase provide me via email list of strings used in the installer?

I will reply with italian translation.

Thanks.

**Comment by guidefloripa** [comment]
I’m separating the strings from the code of the installer and putting in the GitHub.

I’ll tell you when it’s ready.

Thanks
